### ISSUE TITLE
Twitter BOTの実装を考える

### ISSUE THREAD

**Issue by Tiger1422** [give-me-15-min/Twitter-Bot#2]
Twitter APIにどのような機能があるかを探してどのように実装するか検討。

検討する際は以下の項目に注視する

#### 例:
* DM
* リプライ
* タイムライン

#### 例:
* BOTからDM,
* ツイートに直接BOTがリプライを送信
* 別アプリが，Twitterクライアントとして動作し，通知を飛ばす

**Comment by akakou** [comment]
リプライにメッセージを飛ばすを優先して開発をする。

**Comment by akakou** [comment]
**実装の予定**
~ツイートを検索するAPIを利用。~
~その検索結果を絞る情報として、ユーザのアカウント名を使用。~

**Comment by akakou** [comment]
https://developer.twitter.com/en/docs/tweets/search/api-reference/get-search-tweets.html

**Comment by akakou** [comment]
tweepy ?

**Comment by Robin1421** [comment]
*使用する可能性のあるやつ*
* **リプライを取得**
* ダイレクトメッセージを取得
* **リプライに送信**
* ダイレクトメッセージに送信

**Comment by Robin1421** [comment]
リプライ取得の方法
* 検索APIを使い保護対象者へのリプライすべてを取得

**Comment by Robin1421** [comment]
これを使う
https://developer.twitter.com/en/docs/tweets/search/overview
