### ISSUE TITLE
twitter api トークンを取得する

### ISSUE THREAD

**Issue by Robin1421** [give-me-15-min/Twitter-Bot#5]
* [Twitterのアクセストークン等の取得方法とDirectメッセージを取得するために必要な設定](http://kageura.hatenadiary.jp/entry/2018/01/02/Twitter%E3%81%AE%E3%82%A2%E3%82%AF%E3%82%BB%E3%82%B9%E3%83%88%E3%83%BC%E3%82%AF%E3%83%B3%E7%AD%89%E3%81%AE%E5%8F%96%E5%BE%97%E6%96%B9%E6%B3%95%E3%81%A8Direct%E3%83%A1%E3%83%83%E3%82%BB%E3%83%BC%E3%82%B8)
* [Interested in a developer account?](https://developer.twitter.com/en/apply/user)

**Comment by akakou** [comment]
どした？
